### ISSUE TITLE
4_face_recognize 发现一个报错

### ISSUE THREAD

**Issue by sadrookie** [Dragon-GCS/Python#1]
_环境是：tf2.3.0+python3.8_
  在pycharm中运行4_face_recognize报错如下：
File "D:\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\python\keras\layers\merge.py", line 519, in build
    raise ValueError(err_msg)
ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 128, 12, 192), (None, 32, 12, 192), (None, 32, 12, 102), (None, 64, 12, 192)]

  经查询似乎是由于人脸识别模型使用的是channel first格式，通道位于卷积尺寸前而不是常用的channel last格式导致 参数不对应无法拼接

**Comment by Dragon-GCS** [comment]
你只有最后一个报错，没有第一个报错无法定位到具体是哪里出的问题。另外你这个tensor shape也很奇怪，建议检查一下你的输入。想尽快解决问题的话，写在issue里边的东西要尽可能用少的代码让人能够复现出你的错误，

**Comment by sadrookie** [comment]
下面是运行4_face_recognize之后 显示的结果
Traceback (most recent call last):
  File "E:/吴恩达课后作业/Python-master/吴恩达深度学习课后作业/第四周/4_face_recognize.py", line 128, in <module>
    FRmodel = u.faceRecoModel(input_shape=(3, 96, 96))
  File "E:\吴恩达课后作业\Python-master\吴恩达深度学习课后作业\第四周\fr_utils.py", line 396, in faceRecoModel
    X = inception_block_1a(X)
  File "E:\吴恩达课后作业\Python-master\吴恩达深度学习课后作业\第四周\fr_utils.py", line 178, in inception_block_1a
    inception = concatenate([X_3x3, X_5x5, X_pool, X_1x1], axis=1)
  File "D:\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\python\keras\layers\merge.py", line 931, in concatenate
    return Concatenate(axis=axis, **kwargs)(inputs)
  File "D:\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 925, in __call__
    return self._functional_construction_call(inputs, args, kwargs,
  File "D:\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1098, in _functional_construction_call
    self._maybe_build(inputs)
  File "D:\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 2643, in _maybe_build
    self.build(input_shapes)  # pylint:disable=not-callable
  File "D:\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\python\keras\utils\tf_utils.py", line 323, in wrapper
    output_shape = fn(instance, input_shape)
  File "D:\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\python\keras\layers\merge.py", line 519, in build
    raise ValueError(err_msg)
ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 128, 12, 192), (None, 32, 12, 192), (None, 32, 12, 102), (None, 64, 12, 192)]

楼主我还是个初学者，代码都是直接下载的您的git上的   我看不出来哪里有问题

**Comment by sadrookie** [comment]
下面是运行之后结果
Traceback (most recent call last):
  File "E:/吴恩达课后作业/Python-master/吴恩达深度学习课后作业/第四周/4_face_recognize.py", line 128, in <module>
    FRmodel = u.faceRecoModel(input_shape=(3, 96, 96))
  File "E:\吴恩达课后作业\Python-master\吴恩达深度学习课后作业\第四周\fr_utils.py", line 396, in faceRecoModel
    X = inception_block_1a(X)
  File "E:\吴恩达课后作业\Python-master\吴恩达深度学习课后作业\第四周\fr_utils.py", line 178, in inception_block_1a
    inception = concatenate([X_3x3, X_5x5, X_pool, X_1x1], axis=1)
  File "D:\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\python\keras\layers\merge.py", line 931, in concatenate
    return Concatenate(axis=axis, **kwargs)(inputs)
  File "D:\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 925, in __call__
    return self._functional_construction_call(inputs, args, kwargs,
  File "D:\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1098, in _functional_construction_call
    self._maybe_build(inputs)
  File "D:\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 2643, in _maybe_build
    self.build(input_shapes)  # pylint:disable=not-callable
  File "D:\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\python\keras\utils\tf_utils.py", line 323, in wrapper
    output_shape = fn(instance, input_shape)
  File "D:\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\python\keras\layers\merge.py", line 519, in build
    raise ValueError(err_msg)
ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 128, 12, 192), (None, 32, 12, 192), (None, 32, 12, 102), (None, 64, 12, 192)]

楼主 我还是个初学者 是直接下载您的git上的  看不出来哪里有问题

**Comment by sadrookie** [comment]
下面是运行之后的结果
Traceback (most recent call last):
  File "E:/吴恩达课后作业/Python-master/吴恩达深度学习课后作业/第四周/4_face_recognize.py", line 128, in <module>
    FRmodel = u.faceRecoModel(input_shape=(3, 96, 96))
  File "E:\吴恩达课后作业\Python-master\吴恩达深度学习课后作业\第四周\fr_utils.py", line 396, in faceRecoModel
    X = inception_block_1a(X)
  File "E:\吴恩达课后作业\Python-master\吴恩达深度学习课后作业\第四周\fr_utils.py", line 178, in inception_block_1a
    inception = concatenate([X_3x3, X_5x5, X_pool, X_1x1], axis=1)
  File "D:\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\python\keras\layers\merge.py", line 931, in concatenate
    return Concatenate(axis=axis, **kwargs)(inputs)
  File "D:\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 925, in __call__
    return self._functional_construction_call(inputs, args, kwargs,
  File "D:\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1098, in _functional_construction_call
    self._maybe_build(inputs)
  File "D:\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 2643, in _maybe_build
    self.build(input_shapes)  # pylint:disable=not-callable
  File "D:\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\python\keras\utils\tf_utils.py", line 323, in wrapper
    output_shape = fn(instance, input_shape)
  File "D:\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\python\keras\layers\merge.py", line 519, in build
    raise ValueError(err_msg)
ValueError: A Concatenate layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 128, 12, 192), (None, 32, 12, 192), (None, 32, 12, 102), (None, 64, 12, 192)]

楼主我是个初学者 直接下载您git上的  下载不知道是哪里的问题

**Comment by Dragon-GCS** [comment]
我最近今天手头都没有电脑，所以不能很快复现。但是就你这个报错来说，应该是输入图片尺寸不对，识别模型要求输入的图片尺寸96x96，你的输入应该是一个12x192的奇怪的尺寸，建议你再看视频好好学习一下。
过几天我会尝试复现一下，如果有问题会在回复你的，没有问题我就关掉这个issue了。

**Comment by sadrookie** [comment]
好的 我没有问题了  十分感谢百忙之中解答  感谢！

**Comment by Dragon-GCS** [comment]
刚刚运行了一下，你开始的猜测是对的，keras默认的图像格式是channel_last，要修改为channel_first。关于这一点在127我写了注释。windows下的keras配置文件在C:\用户\<用户名>\.keras\keras.json，修改之后我这里是可以正常运行的。

**Comment by Dragon-GCS** [comment]
刚刚运行了一下，你开始的猜测是对的，keras默认的图像格式是channel_last，要修改为channel_first。关于这一点在127我写了注释。windows下的keras配置文件在C:\用户\<用户名>\.keras\keras.json，修改之后我这里是可以正常运行的。
